services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.11
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-proxy-conf:/etc/nginx/conf.d:rw
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-dhparam:/etc/nginx/dhparam:rw
      - nginx-proxy-html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    volumes:
      - nginx-proxy-conf:/etc/nginx/conf.d:ro
      - nginx-proxy-certs:/etc/nginx/certs:rw
      - nginx-proxy-dhparam:/etc/nginx/dhparam:ro
      - nginx-proxy-html:/usr/share/nginx/html:ro
      - acme-data:/etc/acme.sh:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=dvdrelin@gmail.com
    networks:
      - proxy

volumes:
  nginx-proxy-conf:
    driver: local
  nginx-proxy-dhparam:
    driver: local
  nginx-proxy-certs:
    driver: local
  nginx-proxy-html:
    driver: local
  acme-data:
    driver: local

networks:
  proxy:
    name: proxy
