services:
  neon-tetris:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neon-tetris
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VIRTUAL_HOST=ntetris.ddns.net
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
      - ACME_HOST=ntetris.ddns.net
    volumes:
      - ./backend/data:/app/backend/data:rw
    networks:
      - proxy
