version: '3.8'

services:
  neon-tetris:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neon-tetris
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VIRTUAL_HOST=ntetris.ddns.net
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=ntetris.ddns.net
      - LETSENCRYPT_EMAIL=dvdrelin@gmail.com
    volumes:
      - ./backend/data:/app/backend/data:rw
    networks:
      - proxy
    labels:
      - com.docker.compose.version=2
      - com.nginx.proxy-manager=true

networks:
  proxy:
    external: true
    name: proxy
